# Generated by Django 5.0 on 2024-01-08 18:25

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator])),
                ('email', models.EmailField(max_length=200)),
                ('user_type', models.CharField(blank=True, choices=[('Recruiter', 'Recruiter'), ('JobSeeker', 'JobSeeker'), ('Employee', 'Employee'), ('Administrator', 'Administrator'), ('Admin', 'Admin')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('auth_token', models.CharField(blank=True, max_length=500, null=True)),
                ('otp_token', models.CharField(blank=True, max_length=6, null=True)),
                ('is_varified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('custom_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=14)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='jobseeker/profile_picture/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True)),
                ('short_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.custom_user',),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('custom_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('comapany_name', models.CharField(max_length=100)),
                ('comapany_phone_number', models.CharField(max_length=100)),
                ('company_address', models.CharField(blank=True, max_length=500, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('comapany_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.custom_user',),
        ),
    ]
